changes

diff --git a/next-app/Dockerfile b/next-app/Dockerfile
--- a/next-app/Dockerfile
+++ b/next-app/Dockerfile
@@ -27,12 +27,11 @@ COPY . .
 # Uncomment the following line in case you want to disable telemetry during the build.
 # ENV NEXT_TELEMETRY_DISABLED 1
 
-RUN \
-  if [ -f yarn.lock ]; then yarn run build; \
-  elif [ -f package-lock.json ]; then npm run build; \
-  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
-  else echo "Lockfile not found." && exit 1; \
-  fi
+RUN echo "Checking for lock files..." && \
+    if [ -f yarn.lock ]; then echo "Found yarn.lock"; yarn run build; \
+    elif [ -f package-lock.json ]; then echo "Found package-lock.json"; npm run build; \
+    elif [ -f pnpm-lock.yaml ]; then echo "Found pnpm-lock.yaml"; corepack enable pnpm && pnpm run build; \
+    else echo "Lockfile not found." && exit 1; fi
 
 # Production image, copy all the files and run next
 FROM base AS runner
